package tcg.frontend

object Routes {
    const val LOGIN = "login"
    const val ACCESS = "access"
    const val USERS = "users"
    const val USER = "user"
    const val LOGS = "logs"
    const val LOG = "log"
    const val GENERATION = "generation"
    const val EXPANSIONS = "expansions"
    const val EXPANSIONSWIKI = "expansionswiki"
    const val CARDS = "cards"
    const val CARD = "card"
    const val USERCARDS = "usercards"
    const val USERCARD = "usercard"
    const val MARKET = "market"
    const val SELLOFFERS = "selloffers"
    const val SELLOFFERSVIEW = "selloffersview"
    const val EXCHANGEOFFERS = "exhcangeoffers"
    const val EXCHANGEOFFERSVIEW = "exhcangeoffersview"
    const val VIEWSELFOFFERS = "viewselfoffers"
    const val OPENBOOSTER = "openbooster"
    const val OPENBOOSTERVIEW = "openboosterview"
}